import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  formatPhone,
  formatPostal,
  formatAmount,
  groupLikeExample,
  areaCodeLength,
} from '../src/core/numbers.js';
import { AREA_CODE_LENGTH } from '../src/core/jp-area-codes.js';

describe('phone numbers', () => {
  it.each([
    // mobile, IP and M2M: always 3-4-4
    ['09012345678', '090-1234-5678'],
    ['08012345678', '080-1234-5678'],
    ['07012345678', '070-1234-5678'],
    ['05012345678', '050-1234-5678'],
    // non-geographic services with fixed groupings
    ['0120123456', '0120-123-456'],
    ['08001234567', '0800-123-4567'],
    ['0570123456', '0570-123-456'],
  ])('%s -> %s', (digits, expected) => {
    expect(formatPhone(digits)).toBe(expected);
  });

  it.each([
    // Landlines: the area code runs 2 to 5 digits and can only be looked up.
    ['0312345678', '03-1234-5678'],     // Tokyo
    ['0612345678', '06-1234-5678'],     // Osaka
    ['0112345678', '011-234-5678'],     // Sapporo
    ['0451234567', '045-123-4567'],     // Yokohama
    ['0521234567', '052-123-4567'],     // Nagoya
    ['0751234567', '075-123-4567'],     // Kyoto
    ['0927123456', '092-712-3456'],     // Fukuoka
    ['0920401234', '0920-40-1234'],     // Iki: 0920 is its own 4-digit code inside 092
    ['0466123456', '0466-12-3456'],     // Fujisawa
    ['0467123456', '0467-12-3456'],     // Chigasaki
    ['0471001234', '04-7100-1234'],     // Kashiwa: 2-digit area code 04
    ['0126723456', '01267-2-3456'],     // Kuriyama: 5-digit area code
  ])('landline %s -> %s', (digits, expected) => {
    expect(formatPhone(digits)).toBe(expected);
  });

  it.each([
    '0901234567',   // mobile prefix but only ten digits
    '123',
    '090123456789', // too long
    '1234567890',   // no leading zero
    '09O12345678',  // letter O, not zero
    '0921234567',   // 0921 is not in the national numbering plan
    '',
  ])(
    'refuses %s rather than guess',
    (digits) => {
      expect(formatPhone(digits)).toBeNull();
    },
  );
});

describe('postal codes and amounts', () => {
  it('splits a seven-digit postal code', () => {
    expect(formatPostal('1500001')).toBe('150-0001');
    expect(formatPostal('150001')).toBeNull();
  });

  it.each([
    ['5000000', '5,000,000'],
    ['1234', '1,234'],
    ['999', '999'],
    ['1,234,567', '1,234,567'],
    ['12,34', '1,234'],
    ['1234567.89', '1,234,567.89'],
    ['-2500', '-2,500'],
  ])('amount %s -> %s', (text, expected) => {
    expect(formatAmount(text)).toBe(expected);
  });

  it.each(['\\1000', '1000円', 'abc', '1.2.3', ''])('refuses non-amount %s', (text) => {
    expect(formatAmount(text)).toBeNull();
  });

  it("uses an example's grouping only when the digit count matches", () => {
    expect(groupLikeExample('12345678', [4, 4])).toBe('1234-5678');
    expect(groupLikeExample('1234567', [4, 4])).toBeNull();
  });
});

describe('the generated area-code table', () => {
  const SOURCE = readFileSync(join(__dirname, '..', 'src', 'core', 'jp-area-codes.ts'), 'utf8');

  it('is generated, carries its attribution, and is not hand-edited', async () => {
    expect(SOURCE).toContain('GENERATED by scripts/make-area-codes.mjs');
    expect(SOURCE).toContain('出典：総務省ホームページ');
    // Re-rendering the same rules through the generator must reproduce the
    // file byte for byte, so a manual edit can't slip in unnoticed.
    const { renderModule } = await import('../scripts/make-area-codes.mjs');
    const rules = [...AREA_CODE_LENGTH.entries()];
    const header = /Data as of (.*); (\d+) assigned number prefixes/.exec(SOURCE)!;
    const regenerated = renderModule({ rules, dates: header[1]!.split(', '), rows: Number(header[2]) });
    expect(regenerated).toBe(SOURCE);
  });

  it('holds only sane rules', () => {
    expect(AREA_CODE_LENGTH.size).toBeGreaterThan(500);
    for (const [prefix, len] of AREA_CODE_LENGTH) {
      expect(prefix).toMatch(/^0[1-9]\d{0,4}$/);
      expect(len).toBeGreaterThanOrEqual(2);
      expect(len).toBeLessThanOrEqual(5);
    }
  });

  it('resolves a prefix by its longest match', () => {
    expect(areaCodeLength('0467123456')).toBe(4);
    expect(areaCodeLength('0312345678')).toBe(2);
  });
});
