/**
 * Holds the store assets to the dimensions the stores actually require.
 *
 * The images are generated by scripts/make-store-assets.mjs, so an ordinary
 * edit there could change a size without anyone noticing until an upload is
 * rejected — and Edge rejects a promotional tile that is not exactly 440x280.
 * Descriptions are checked against Edge's 250-character floor for the same
 * reason.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '..');
const ASSETS = join(ROOT, 'store', 'assets');

/**
 * Reads width and height straight out of a PNG's IHDR chunk. The project
 * writes PNGs by hand in scripts/make-icons.mjs, so reading one back needs no
 * dependency either.
 */
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(file);
  const signature = buf.subarray(0, 8).toString('hex');
  expect(signature, `${file} is not a PNG`).toBe('89504e470d0a1a0a');
  expect(buf.subarray(12, 16).toString('ascii'), `${file} has no IHDR`).toBe('IHDR');
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/**
 * name -> [width, height]. The same files go to Edge and the Chrome Web Store,
 * and both publish identical requirements for these three.
 */
const REQUIRED: Record<string, [number, number]> = {
  // Edge extension logo: 1:1, 300x300 recommended, 128x128 minimum.
  'store-logo-300.png': [300, 300],
  // Small promotional tile: exact size; required by Chrome, optional on Edge.
  'promo-tile-440x280.png': [440, 280],
  // Marquee / large promotional tile: exact size, optional on both.
  'marquee-1400x560.png': [1400, 560],
};

/**
 * Screenshots have to satisfy both stores at once:
 *   Edge:   1280x800 or 640x480, at most 6
 *   Chrome: 1280x800 or 640x400, at most 5
 * 1280x800 is the only size both accept, and 5 is the tighter count.
 */
const SCREENSHOT_SIZES = [[1280, 800]];
const MAX_SCREENSHOTS = 5;

describe('store assets match what the stores require', () => {
  it('has been generated at all', () => {
    expect(existsSync(ASSETS), 'run `npm run assets`').toBe(true);
  });

  it.each(Object.entries(REQUIRED))('%s is exactly %s', (name, expected) => {
    const { width, height } = pngSize(join(ASSETS, name));
    expect([width, height]).toEqual(expected);
  });

  it('keeps the logo square, as both stores require', () => {
    const { width, height } = pngSize(join(ASSETS, 'store-logo-300.png'));
    expect(width).toBe(height);
    expect(width).toBeGreaterThanOrEqual(128);
  });

  it('has one to five screenshots, each at a size both stores accept', () => {
    const shots = readdirSync(ASSETS).filter((f) => f.startsWith('screenshot-') && f.endsWith('.png'));
    expect(shots.length).toBeGreaterThanOrEqual(1);
    expect(shots.length, 'the Chrome Web Store accepts at most 5 screenshots').toBeLessThanOrEqual(
      MAX_SCREENSHOTS,
    );

    for (const shot of shots) {
      const { width, height } = pngSize(join(ASSETS, shot));
      expect(
        SCREENSHOT_SIZES.some(([w, h]) => w === width && h === height),
        `${shot} is ${width}x${height}; only 1280x800 is accepted by both Edge and Chrome`,
      ).toBe(true);
    }
  });

  it('ships the square toolbar icons the manifest names', () => {
    for (const size of [16, 32, 48, 128]) {
      const { width, height } = pngSize(join(ROOT, 'public', 'icons', `icon${size}.png`));
      expect([width, height], `icon${size}.png`).toEqual([size, size]);
    }
  });

  it('uses the artwork in art/ for the package and the Edge logo', () => {
    // The 128px icon is the artwork itself, not a re-render of it.
    expect(
      readFileSync(join(ROOT, 'public', 'icons', 'icon128.png')).equals(
        readFileSync(join(ROOT, 'art', 'icon-128.png')),
      ),
    ).toBe(true);
    expect(pngSize(join(ROOT, 'art', 'icon-300.png'))).toEqual({ width: 300, height: 300 });
    expect(pngSize(join(ROOT, 'art', 'icon-128.png'))).toEqual({ width: 128, height: 128 });
  });

  it('keeps icon backgrounds transparent, so toolbars show through', () => {
    // PNG colour type 6 is RGBA: the icons must carry an alpha channel.
    for (const size of [16, 32, 48, 128]) {
      const buf = readFileSync(join(ROOT, 'public', 'icons', `icon${size}.png`));
      expect(buf[25], `icon${size}.png colour type`).toBe(6);
    }
  });
});

describe('listing copy fits the store limits', () => {
  const listing = readFileSync(join(ROOT, 'store', 'listing.md'), 'utf8');
  const blocks = [...listing.matchAll(/```\n([\s\S]*?)```/g)].map((m) => m[1]!.trim());

  it('carries a long description in both languages', () => {
    // Edge requires 250-10,000 characters. The two long blocks are the English
    // and Japanese descriptions.
    const long = blocks.filter((b) => b.length >= 250);
    expect(long.length, 'expected an English and a Japanese description').toBeGreaterThanOrEqual(2);
    for (const b of long) expect(b.length).toBeLessThanOrEqual(10_000);
  });

  it('has a Japanese description, since the audience reads Japanese', () => {
    const japanese = blocks.filter(
      (b) => b.length >= 250 && [...b].filter((c) => c >= '぀' && c <= '鿿').length > 200,
    );
    expect(japanese.length).toBeGreaterThanOrEqual(1);
  });

});

/**
 * The manifest's name and description are __MSG_…__ placeholders resolved from
 * _locales/, because the Chrome Web Store only offers a store listing in the
 * languages the package ships. A missing key shows the raw placeholder text on
 * the listing, so every placeholder must resolve in every shipped language.
 */
describe.each(['chrome', 'firefox'] as const)('%s package localisation', (target) => {
  const dist = join(ROOT, 'dist', target);
  const manifest = JSON.parse(readFileSync(join(dist, 'manifest.json'), 'utf8'));
  const locales = readdirSync(join(dist, '_locales'));
  const messages = (lang: string): Record<string, { message: string }> =>
    JSON.parse(readFileSync(join(dist, '_locales', lang, 'messages.json'), 'utf8'));

  /** Every __MSG_key__ placeholder anywhere in the manifest. */
  const placeholders = [...JSON.stringify(manifest).matchAll(/__MSG_(\w+)__/g)].map((m) => m[1]!);

  it('ships English and Japanese, with English as the default', () => {
    expect(locales.sort()).toEqual(['en', 'ja']);
    expect(manifest.default_locale).toBe('en');
  });

  it('uses placeholders for the strings the stores display', () => {
    expect(placeholders).toEqual(expect.arrayContaining(['extName', 'extDescription']));
  });

  it.each(['en', 'ja'])('resolves every placeholder in %s', (lang) => {
    const table = messages(lang);
    for (const key of placeholders) {
      expect(table[key]?.message, `${lang} is missing "${key}"`).toBeTruthy();
    }
  });

  it.each(['en', 'ja'])('keeps the %s name and description within Chrome limits', (lang) => {
    // Chrome's manifest reference: name at most 75 characters, description
    // at most 132. The description doubles as the store's short description.
    const table = messages(lang);
    expect(table.extName!.message.length).toBeLessThanOrEqual(75);
    expect(table.extDescription!.message.length).toBeGreaterThan(0);
    expect(table.extDescription!.message.length).toBeLessThanOrEqual(132);
  });

  it('has a Japanese description that is actually Japanese', () => {
    const ja = messages('ja').extDescription!.message;
    expect([...ja].filter((c) => c >= '぀' && c <= '鿿').length).toBeGreaterThan(20);
  });
});
