/**
 * Holds the store assets to the dimensions the stores actually require.
 *
 * The images are generated by scripts/make-store-assets.mjs, so an ordinary
 * edit there could change a size without anyone noticing until an upload is
 * rejected — and Edge rejects a promotional tile that is not exactly 440x280.
 * Descriptions are checked against Edge's 250-character floor for the same
 * reason.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '..');
const ASSETS = join(ROOT, 'store', 'assets');

/**
 * Reads width and height straight out of a PNG's IHDR chunk. The project
 * writes PNGs by hand in scripts/make-icons.mjs, so reading one back needs no
 * dependency either.
 */
function pngSize(file: string): { width: number; height: number } {
  const buf = readFileSync(file);
  const signature = buf.subarray(0, 8).toString('hex');
  expect(signature, `${file} is not a PNG`).toBe('89504e470d0a1a0a');
  expect(buf.subarray(12, 16).toString('ascii'), `${file} has no IHDR`).toBe('IHDR');
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/** name -> [width, height], per Microsoft's published requirements. */
const REQUIRED: Record<string, [number, number]> = {
  // Extension logo: 1:1, 300x300 recommended, 128x128 minimum.
  'store-logo-300.png': [300, 300],
  // Small promotional tile: must be exactly this size.
  'promo-tile-440x280.png': [440, 280],
  // Large promotional tile: must be exactly this size.
  'marquee-1400x560.png': [1400, 560],
};

/** Edge accepts screenshots at either of these sizes, and at most six. */
const SCREENSHOT_SIZES = [
  [1280, 800],
  [640, 480],
];

describe('store assets match what the stores require', () => {
  it('has been generated at all', () => {
    expect(existsSync(ASSETS), 'run `npm run assets`').toBe(true);
  });

  it.each(Object.entries(REQUIRED))('%s is exactly %s', (name, expected) => {
    const { width, height } = pngSize(join(ASSETS, name));
    expect([width, height]).toEqual(expected);
  });

  it('keeps the logo square, as both stores require', () => {
    const { width, height } = pngSize(join(ASSETS, 'store-logo-300.png'));
    expect(width).toBe(height);
    expect(width).toBeGreaterThanOrEqual(128);
  });

  it('has between one and six screenshots, each at an accepted size', () => {
    const shots = readdirSync(ASSETS).filter((f) => f.startsWith('screenshot-') && f.endsWith('.png'));
    expect(shots.length).toBeGreaterThanOrEqual(1);
    expect(shots.length, 'Edge accepts at most 6 screenshots').toBeLessThanOrEqual(6);

    for (const shot of shots) {
      const { width, height } = pngSize(join(ASSETS, shot));
      expect(
        SCREENSHOT_SIZES.some(([w, h]) => w === width && h === height),
        `${shot} is ${width}x${height}; Edge accepts only 1280x800 or 640x480`,
      ).toBe(true);
    }
  });

  it('ships the square toolbar icons the manifest names', () => {
    for (const size of [16, 32, 48, 128]) {
      const { width, height } = pngSize(join(ROOT, 'public', 'icons', `icon${size}.png`));
      expect([width, height], `icon${size}.png`).toEqual([size, size]);
    }
  });
});

describe('listing copy fits the store limits', () => {
  const listing = readFileSync(join(ROOT, 'store', 'listing.md'), 'utf8');
  const blocks = [...listing.matchAll(/```\n([\s\S]*?)```/g)].map((m) => m[1]!.trim());

  it('carries a long description in both languages', () => {
    // Edge requires 250-10,000 characters. The two long blocks are the English
    // and Japanese descriptions.
    const long = blocks.filter((b) => b.length >= 250);
    expect(long.length, 'expected an English and a Japanese description').toBeGreaterThanOrEqual(2);
    for (const b of long) expect(b.length).toBeLessThanOrEqual(10_000);
  });

  it('has a Japanese description, since the audience reads Japanese', () => {
    const japanese = blocks.filter(
      (b) => b.length >= 250 && [...b].filter((c) => c >= '぀' && c <= '鿿').length > 200,
    );
    expect(japanese.length).toBeGreaterThanOrEqual(1);
  });

  it('keeps the manifest short description within Edge display limits', () => {
    const manifest = JSON.parse(readFileSync(join(ROOT, 'dist', 'chrome', 'manifest.json'), 'utf8'));
    // Edge shows the manifest description as the listing's short description.
    expect(manifest.description.length).toBeGreaterThan(0);
    expect(manifest.description.length).toBeLessThanOrEqual(132);
  });
});
